apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentd-es
  namespace: devops
  labels:
    k8s-app: {{ .Release.Name }}-fluentd-es
    version: "{{ .Values.fluentd.version }}"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-fluentd-es
      version: "{{ .Values.fluentd.version }}"
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-fluentd-es
        kubernetes.io/cluster-service: "true"
        version: {{ .Values.fluentd.version }}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    spec:
      serviceAccountName: {{ .Release.Name }}-fluentd-es
      containers:
      - name: fluentd-es
        image: k8s.gcr.io/fluentd-elasticsearch:{{ .Values.fluentd.version }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
        - name: u01
          mountPath: /u01
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: u01
        hostPath:
          path: /u01
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-fluentd-es-config
