apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-fluentd-es
  namespace: devops
  labels:
    k8s-app: {{ .Release.Name }}-fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-fluentd-es
  labels:
    k8s-app: {{ .Release.Name }}-fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-fluentd-es
  labels:
    k8s-app: {{ .Release.Name }}-fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-fluentd-es
  namespace: devops
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-fluentd-es
  apiGroup: ""
---
# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-elasticsearch-logging
  namespace: devops
  labels:
    k8s-app: {{ .Release.Name }}-elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-elasticsearch-logging
  labels:
    k8s-app: {{ .Release.Name }}-elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: {{ .Release.Name }}-elasticsearch-logging
  labels:
    k8s-app: {{ .Release.Name }}-elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-elasticsearch-logging
  namespace: devops
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-elasticsearch-logging
  apiGroup: ""
